# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Setecna REG system
version: "0.1.0"
slug: setecna
description: Setecna REG system web integration
url: "https://github.com/Ingordigia/homeassistant-addon-setecna"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  systemID: null
  username: null
  password: null
schema:
  systemID: "str"
  username: "str"
  password: "password"
image: "ghcr.io/ingordigia/{arch}-setecna-addon"
